import requests
import streamlit as st
from streamlit_option_menu import option_menu
from streamlit_lottie import st_lottie
from streamlit_extras.let_it_rain import rain
from PIL import Image


# --- Konfiguration ---
st.set_page_config(page_title="Die Alkocops", page_icon="🍺", layout="wide")

def load_lottieurl(url):
    r = requests.get(url)
    if r.status_code != 200:
        return None
    return r.json()

# Use local CSS
def local_css(file_name):
    with open(file_name) as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

local_css("style/style.css")

# ---- LOAD ASSETS ----
lottie_rock = load_lottieurl("https://lottie.host/c27869d1-603f-4f6e-9b91-fc2cf17c128d/xnNh83q1DP.json")
lottie_bier = load_lottieurl("https://lottie.host/95df498a-2d7a-4abb-8eb3-a8542f8759f7/Mbflv91AhA.json")

img_band1 = Image.open("images/foto1.jpg")
img_band2 = Image.open("images/foto2.jpg")

html_code_spotify = '''
<iframe style="border-radius:0px" src="https://open.spotify.com/embed/artist/6UolTF33q9gCE3kDK6tuTU?utm_source=generator&theme=0" width="100%" height="600" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
'''

html_code_live = '''
<iframe width="560" height="315" src="https://www.youtube.com/embed/pCQnWvyQ54Y?si=O-3ZX5K6sSvNA9wP&amp;controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
'''

st.title("Die Alkocops 🍻👮‍♂️")
tab_titles = [
    "Start",
    "Konzerte",
    "Texte"
]

tabs = st.tabs(tab_titles)

with tabs[0]:
    with st.container():
        text_column, image_column = st.columns(2)
        with text_column:
            st.subheader("¿Qué pasa cabrones?")
            st.title("Wir sind die Alkocops! 🍻")
            st.write("Ob Wohnungsmarkt, Clubsterben oder Craftbier: Die Alkocops haben etwas dagegen. Laut ChatGPT sind ihre Lieder wohl eine ''sozialkritische Faust ins Gesicht'', aber bescheiden wie sie sind, konzentrieren sie sich lieber auf das Wesentliche: Dosenbier verhaften!")
            st.write(" ")
            st.write("Die Alkocops sind Florian Silberblick, Huckleberry Gin, Marius Müller-Thurgau, Dr. Don Promillo und Toni Pilsetti.")
            st.write(" ")
            st.write("[ 📸 Instagram >](https://www.instagram.com/alkocops/?hl=de)")
            st.write("[ 🎵 Spotify >](https://open.spotify.com/intl-de/artist/6UolTF33q9gCE3kDK6tuTU?si=up3DRDMuQs6PF3vsJ1ZHhQ)")
            st.write("[ 🏕 Bandcamp >](https://diealkocops.bandcamp.com/)")
            st.write("[ 🎥 YouTube >](https://www.youtube.com/@diealkocops6613)")
            st.write(" ")
        with image_column:
            st.image(img_band2)

    # ---- SPOTIFY ----
    with st.container():
        st.write("---")
        left_column, right_column = st.columns(2)
        with left_column:
            st.header("Flüssiges Gold")
            st.write("Goldfarben, naturtrüb und mit vollmundigem Geschmack ist das Album ''Flüssiges Gold'' der Alkocops eine ehrliche Erfrischung. Ein wahrhaft gutes Album kann nur entstehen, wenn man von allem nur das Beste nimmt. Kompromisslos.")
            st.write("Weil uns das Wohl anspruchsvoller Kenner am Herzen liegt. Und weil ''Flüssiges Gold'' immer das bleiben soll, was es akzeptiertermaßen ist: Eines der süffigsten Alben unserer Zeit.")
            st.write(" ")
        with right_column:
            st.write(html_code_spotify, unsafe_allow_html=True)

with tabs[1]:
# ---- KONZERTE ---- 
    rain(
        emoji="🍻",
        font_size=54,
        falling_speed=5,
        animation_length="infinite",
    )
    with st.container():
        left_column, right_column = st.columns(2)
        with right_column:
            st.write(html_code_live, unsafe_allow_html=True) 
        with left_column:
            st.header("Konzerte")
            st.subheader("2024:")
            st.write("18.05. // Sonnenkeller Balingen // The Snouts und Der Ganze Rest")
            st.write("05.04. // Schlosskeller Emmendingen // Wagner Brutal")
            st.write("23.03. // Laut für Vielfalt! im SAK Lörrach // Skabooom")
            st.write("09.03. // Schlosskeller Emmendingen // Nevermind")
            st.write(" ")
            st.subheader("2023:")
            st.write("15.12. // Crash Freiburg // ")
            st.write("09.08. // Café Atlantik Freiburg // Maid of Ace")
            st.write("22.04. // Battle to Exist in der Alten VHS Bonn // Die Manfreds")
            st.write(" ")
            st.subheader("2022:")
            st.write("19.11. // Schlosskeller Emmendingen // The Snouts & Skaboom")
            st.write("05.11. // DISTROY Festival in der KTS Freiburg // ")
            st.write("21.10. // Rockcafé Altdorf // KID-O")
            st.write("24.09. // Eimer Freiburg // Area South")
            st.write("08.07. // Reboot Festival im Eschholzpark Freiburg // ")
            st.write("26.06. // Freiburg stimmt ein im Artik Freiburg // ")
            st.write("18.06. // Cool Club Kinderweide in Königsfeld // Skabooom")
            st.write("14.05. // Album-Release-Party im JuZe Emmendingen // Skabooom")
            st.write(" ")
            st.subheader("2021:")
            st.write("16.10. // JuZe Denzlingen // Skabooom & Zirka")
            st.write("04.07. // Freiburg stimmt ein im Artik Freiburg // ")
            st.write(" ")
            st.subheader("2020:")
            st.write("09.05. // Corona-Livestream aus dem JuZe Emmendingen // ")
            st.write(" ")
            st.subheader("2019:")
            st.write("23.06. // KTS Freiburg // Heavy Kind & Vain")
            st.write("06.04. // Hinterhaus Emmendingen // ")        
            st.write("Irgendwann mal // White Rabbit Freiburg // ")
            st.write(" ")
            st.subheader("2018:")
            st.write("29.09. // Jugendzentrum Stühlinger // The Privateers")
            st.write("15.08. // White Rabbit Freiburg // ")
            st.write(" ")

with tabs[2]:
# --- LYRICS ---
    left_column, right_column = st.columns(2)
    with left_column:
            st.subheader("Viva Alkocops")
            st.write("Wer hat ein Mittel gegen Krebs entdeckt? ")
            st.write("Vor wem hat selbst Bushido Respekt?")
            st.write("Und ihr Bankkonto ist immer im grünen Bereich, ")
            st.write("Manche werden schon bei der Erwähnung feucht!")
            st.write("Wenn irgendein blinder Bayer in der Bundesliga trifft,")
            st.write("Widmet er Ihnen stets das räudige Goal!")
            st.write("Und in Mathe hatten sie immer eine Eins, ")
            st.write("Nein, ein Autogramm geben sie dir keins.")
            st.write(" ")
            st.write("Es sind die Alkocops die duften Typen, ")
            st.write("Es sind die Alkocops, die Motherfucker des Undergrounds.")
            st.write("Viva Alkocops, Viva Alkocops, ")
            st.write("das Volk jubelt ihnen zu wie einem Diktator von 'nem Inselstaat.")
            st.write(" ")
            st.write("Sie sind die coolste Band hier in der Stadt, ")
            st.write("Sie machen in 'ner Keilerei an die hundert Studenten platt!")
            st.write("Wenn Merkel auf der Straße demonstriert, ")
            st.write("Kanalisiert sich ihre Wut: „Danke Alkocops“!")
            st.write("Wer inspirierte sämtlichen sehr guten Songs? ")
            st.write("Wer verzichtet auf tribal shit und Bongo Drums?")
            st.write("Und ihr soziales Engagement verschämt selbst Bono von U2, ")
            st.write("Denn er ist ein Loser - genau wie du!")
            st.write(" ")
            st.write("Es sind die Alkocops die duften Typen, ")
            st.write("Es sind die Alkocops, die Motherfucker des Undergrounds.")
            st.write("Viva Alkocops, Viva Alkocops, das Volk jubelt ihnen zu wie dem Diktator von 'nem Inselstaat.")
            st.write(" ")
            st.write(" ")
            st.write(" ")
            st.subheader("FIFA")
            st.write("Zusammen chillt ihr in der Villa von eurem Oberlauch, ")
            st.write("Pinselt euch dabei gegenseitig den Bauch.")
            st.write("Durch die toten Hallen dringt ein fieses Lachen,")
            st.write("Thema der Sitzung heute: Wie kann man Fussball beschissen machen?")
            st.write("")
            st.write("UEFA, FIFA, was habt ihr geraucht?")
            st.write("Eure Symphatiepunkte habt ihr damit aufgebraucht!")
            st.write("Schiebung bei WM-Vergabe ist mir scheißegal,")
            st.write("Doch kein Bier im Stadion, das ist ein Skandal!")
            st.write("")
            st.write("Früher Profifussballspieler, jetzt ein Profihurensohn,")
            st.write("Ohne Fans kein Fussball. Undank ist der Weltenlohn")
            st.write("Auf der VIP-Tribüne zieht Waldi sich drei Weizen rein,")
            st.write("Wahre Fans verdursten, doch das interessiert keinen!")
            st.write("")
            st.write("UEFA, FIFA, was habt ihr geraucht?")
            st.write("Eure Symphatiepunkte habt ihr damit aufgebraucht!")
            st.write("Schiebung bei WM-Vergabe ist mir scheißegal,")
            st.write("Doch kein Bier im Stadion, das ist ein Skandal!")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Marius Müller Miethai")
            st.write("Es klopft an der Tür, jemand will hinein,")
            st.write("Das kann nur Marius Müller-Thurgau sein.")
            st.write("Er will seine Miete jetzt bar Kralle,")
            st.write("Du bist getappt in seine Mietpreisfalle.")
            st.write("Wie du kannst nicht zahlen? Mir kommen die Tränen,")
            st.write("Das entlockt dem Miethai nur ein müdes Gähnen.")
            st.write("In 24 Stunden tauchen die Gorillas auf")
            st.write("Und hauen auf deinen Schädel mit einem Basey drauf")
            st.write("")
            st.write("Der Wohnungsmarkt — ein Haifischbecken,")
            st.write("Du kannst dich nicht vor dem dicksten Hai verstecken.")
            st.write("Marius Müller-Thurgau hat dein Blut geleckt,")
            st.write("Er nährt sich an deinem Cash, es hat ihm gut geschmeckt.")
            st.write("")
            st.write("Die abgesiffte Winzwohnung im Monat tausend Steine,")
            st.write("Wie du kannst die nicht zahlen, dann bricht er dir die Beine.")
            st.write("Du hast nicht genug Kohle, doch du mühst dich sehr,")
            st.write("Marius scheißegal, dann arbeite halt mehr.")
            st.write("Er kommt in deine Wohnung, streicht dir einmal über die Wand,")
            st.write("Diese Renovierung war wichtig — Mietpreiserhöhung!")
            st.write("Du schuftest jeden Tag und deine Kinder Pfandpiraten.")
            st.write("Marius kauft ein paar Häuser, er kriegt einen Harten.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Die Bierhand Gottes")
            st.write("Samstagabend, endlich ist es soweit.")
            st.write("Die Woche ist beendet, zum Feiern bereit.")
            st.write("Seit Tagen freust du dich auf diesen Moment.")
            st.write("Mit deinen Freunden feiern, ganz in deinem Element.")
            st.write("Doch auf der Tanzfläche rückt dir jemand auf die Pelle.")
            st.write("Schlagartig bekommst du von hinten eine Schelle.")
            st.write("Mit Maxi solltest du dir es lieber nicht verkacken.")
            st.write("Die Bierhand Gottes landet in deinem Nacken!")
            st.write("")
            st.write("Die Bierhand Gottes sorgt für Gerechtigkeit,")
            st.write("Eine Schelle in den Nacken ist liebevoll gemeint!")
            st.write("Wer eine Bierhand abbekommt, hat sie auch verdient.")
            st.write("Also halt deine Klappe, für heute bist du bedient.")
            st.write("")
            st.write("Die Bierhand Gottes wacht nachts über der Stadt.")
            st.write("Wo immer Ungerechtigkeit passiert, macht sie die Ungerechten platt.")
            st.write("Vor der Bierhand Gottes werden große Menschen klein.")
            st.write("Was tanzt du auf meiner Tanzfläche - eine gerechte Strafe muss sein!")
            st.write("In die Handfläche wird ein Bier geschenkt und die Bierhand ist geladen,")
            st.write("Einmal richtig zugehauen und schon geht dein Nacken baden.")
            st.write("Man sieht sie nicht kommen. Plötzlich wird es feucht am Kragen.")
            st.write("Die Bierhand Gottes hat wieder einmal zugeschlagen. ")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Mit der Fußmaschine zur Tanke")
            st.write("Diesen Sommer gibt es die Empfehlung")
            st.write("Zu Urlaub in der heimischen Region,")
            st.write("Das ist für mich von Vorteil,")
            st.write("Denn die wichtigsten Urlaubsziele kenne ich schon:")
            st.write("Shell natürlich und Tankhof Grün")
            st.write("Und auf jeden Fall insbesondere Aral.")
            st.write("Sie verkaufen das Wasser des Urlaubs")
            st.write("Zur Befüllung vom knochentrockenen Kanal")
            st.write("")
            st.write("Mit der Fußmaschine zur Tanke, ")
            st.write("Dosenbier kaufen der Gedanke.")
            st.write("Gib' die Kaltschale jetzt endlich her,")
            st.write("Es dürstet mich - sehr!")
            st.write("Mit der Fußmaschine zur Tanke,")
            st.write("Billiges Dosenbier. Bitteschön, Danke. ")
            st.write("Komm mal her jetzt, ich hab' Kaltschalen bestellt,")
            st.write("Und nimm dafür mein rotes Kleingeld.")
            st.write("")
            st.write("An der Tanke kauf' ich sicher kein Craftbier")
            st.write("Und auch keinen Fall Club Mate,")
            st.write("Wenn der Tankwart mir das anbietet,")
            st.write("Würde ich ihn verprügeln!")
            st.write("Das ist a) nämlich viel zu teuer ")
            st.write("Und b) schmeckt's nach grindigem Kanal,")
            st.write("Im Gegensatz dazu überzeugt")
            st.write("Dosenbier im Geschmack total.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Jürgen Klinsmann")
            st.write("Neulich stand ich wie immer am Imbiss und aß eine 1-Meter-Bratwurst. ")
            st.write("Früher war ich hier immer zusammen, zusammen mit Jürgen Klinsmann. ")
            st.write("Wir teilten so ziemlich alles, tranken so manchen über den Durst. ")
            st.write("Doch heute bin ich alleine. Jürgen, was ist los mit dir?")
            st.write("")
            st.write("Ooooh - Jürgen Klinsmann, du hast dich sehr verändert.")
            st.write("Früher warst du ein gern gesehener Partygast, ")
            st.write("Doch heute bist du nicht mehr so cool! Ooooh - Jürgen Klinsmann, du hast dich sehr verändert: ")
            st.write("Früher warst du ein gern gesehener Partygast, ")
            st.write("doch heute spielst du DOTA 2. ")
            st.write("")
            st.write("Immer wenn man dich mal zufällig trifft, bist du voll auf Speed. ")
            st.write("Neulich hast du vergessen, mir zum Geburtstag zu gratulieren. ")
            st.write("Du versucht es, doch du entkommst der Realität nicht. ")
            st.write("Jürgen Klinsmann, bitte , komm zurück ans Licht!")
            st.write("")
            st.write("Ooooh - Jürgen Klinsmann, du hast dich sehr verändert: ")
            st.write("Früher spielten wir Federball, doch jetzt spielst du DOTA am PC. Ooooh - Jürgen Klinsmann, du hast dich sehr verändert: ")
            st.write("Früher spielten wir Laufen-Saufen, doch jetzt spielst High Card Low Card mit dir selbst!")
            st.write("")
            st.write("Ooooh - Jürgen Klinsmann, du hast dich sehr verändert: ")
            st.write("Doch ich gebe nicht auf. Ich kämpfe für dich. Ooooh - Jürgen Klinsmann, du hast dich sehr verändert: ")
            st.write("Gemeinsam schaffen wir es aus deiner Krise, alle zusammen Hand in Hand.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Reise nach Moncao")
            st.write("Fürst Big A und Marius gönnen sich in Monaco lecker Wein")
            st.write("Der nächste Impuls treibt sie in einen Saunaclub hinein. ")
            st.write("Sie verlassen den Club, die Schlampen werden geprellt")
            st.write("Wer hat drei Flaschen Möet auf meine Rechnung bestellt?")
            st.write(" Es ist Marius von den Alkocops, ")
            st.write("Er ist mit der High Society per du.")
            st.write("Er feiert in Monaco mit dem Fürsten und der Crew.")
            st.write("")
            st.write("Ein Champus-Wettsaufen wird von Marius losgetreten, ")
            st.write("Alles mit einem Adelstitel wird zur Teilnahme gebeten.  Marius gewinnt natürlich, wie könnte es anders sein? ")
            st.write("Trotzdem passt noch einiges an Drogen in ihn rein!")
            st.write(" Du bist doch mein bester Freund, lallt der Fürst im Suff.")
            st.write("Er kriegt ’nen fetten Schulterklapps. Junge, ist der Druff! ")
            st.write("Ich mag dich doch auch, du weißt, du bist mein Lieblingsfürst. ")
            st.write("Ich geh’ nochmal kurz an die Bar, ich habe noch etwas Durst. ")
            st.write("Der Fürst kriecht unter dem Tisch herum, denn er kann nicht mehr")
            st.write("Doch Marius lässt ihn nicht und holt noch zwei Bier her. ")
            st.write("Ob Monaco oder Mallotze, wo man sich bepichelt ist egal")
            st.write("Ob Designeranzug oder Badehose, alle asozial!")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Schönster Koch")
            st.write("Ich stehe vor dem Herd mit meiner Kochschürze an,")
            st.write("Vor mir hängt ein Spiegel, damit ich mich sehen kann.")
            st.write("Hinter mir ist eine Videokamera installiert,")
            st.write("Nach dem Kochen wird die Zeitlupe analysiert.")
            st.write("")
            st.write("Man nennt mich nicht umsonst den schönsten Koch,")
            st.write("Was ich koche schmeckt immer sehr gut,")
            st.write("Man nennt mich nicht umsonst den schönsten Koch,")
            st.write("Gesundes Essen ist meine Passion!")
            st.write("")
            st.write("Heute koche ich ein schmackhaftes Faust-Sandwich,")
            st.write("Dazu nutze ich natürlich den Sandwichmaker.")
            st.write("Jemand der behauptet ich sei nicht der schönste Koch,")
            st.write("Schönster-Koch-Fäuste-Vendetta")
            st.write("")
            st.write("Ein Proteingetränk und Wurst mit Ei,")
            st.write("Sind bei einer gesunden Ernährung dabei.")
            st.write("Kaffee und Spaghetti mit Tomatensoße,")
            st.write("Dazu ein bisschen Thunfisch aus der Dose.")
            st.write("Literweise Red Bull und ein Beutel Tabak")
            st.write("Runden dann eigentlich die Ernährung ab.")
            st.write("Wenn du davon dann Durchfall beziehst,")
            st.write("Dann ist das immer ein gutes Zeichen.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Wurstheimat")
            st.write("Machen sie die Schnauze auf platzen mir meine Ohren")
            st.write("Ehre, Stolz, Wurst und Heimat, welche Wurzeln gehen verloren?")
            st.write("Schreiben sie Kommentare geht main Puls auf 210")
            st.write("Sie filmen mich, das dürfen sie nicht. Ich will keine Blaubraunen sehen.")
            st.write("")
            st.write("Fick dich")
            st.write("Hässlich wie die Nacht")
            st.write("Grässlich, Glatze")
            st.write("Hab' dich ausgelacht")
            st.write("")
            st.write("Sie glauben an deutsche Tugend, trinken dennoch viel zu viel")
            st.write("Sind nur dicht und keine Denker. Uniformen ohne Stil. ")
            st.write("12 Jahre Fliegenschiss. Opa Gauland hat gepennt.")
            st.write("Stolz sein auf das Vaterland, weil man sonst nichts anderes kennt")
            st.write("")
            st.write("Ja ich weiß, man soll niemals Andere beleidigen")
            st.write("Doch bei so viel ekelhaften Rassismus und patriotischen Rumgewichse")
            st.write("Muss man auch mal die verbale Dummkeule schwingen")
            st.write("Was anderes verstehen die doch in ihren Sumpf eh nicht mehr")
            st.write("Die strunzdummen Amöben mit ihren Adolf-Tattoos und Bernd-Höcke-Actionfiguren.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Toni Motherfucker")
            st.write("Nachts auf der Straße, die Beleuchtung fällt aus.")
            st.write("Toni tritt aus dem Schatten heraus.")
            st.write("Meine Freunde nicht mehr da, wie kann das sein? ")
            st.write("Mein Hoden schrumpft in den Körper hinein!")
            st.write("Toni ist mächtig, das wird ihm bescheinigt.")
            st.write("Hätt' ich ihn doch nicht auf Facebook entliked.")
            st.write("Auf einmal wird mir klar, gleich beiß' ich ins Gras, ")
            st.write("Ein letzter Versuch: Toni war doch nur Spaß!")
            st.write("")
            st.write("Das verzweifelte Flehen funktioniert natürlich nicht, ")
            st.write("Die schaufelgroße Hand klatscht mir ins Gesicht.")
            st.write("Mein lauchiger Körper, er küsst den Asphalt, ")
            st.write("Ich merke, meine Hose wird nasskalt.")
            st.write("Wie dumm von mir, diese Respektlosigkeit, ")
            st.write("Wird seid jeher mit dem Tode verurteilt.")
            st.write("Das letzte was ich tu, ich bete zu Gott, ")
            st.write("Dann schlägt Toni mir ein Loch in meinen Kopf.")
            st.write("")
            st.write("1,2,3 Toni kommt vorbei ")
            st.write("Und schlägt dir dann dein Face zu Brei")
            st.write("Wenn du dreimal in den Spiegel Toni sprichst, ")
            st.write("Dann kommt er zu dir und tritt dir ins Gesicht.")
            st.write("")
            st.write("Toni Motherfucker.")
            st.write("Toni Motherfucker.")
            st.write("Toni Motherfucker.")
            st.write("Toni Crazy Motherfucker.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Bierbike über die Alpen")
            st.write("Die Ellenbogen auf dem Tisch, die Hände fest am Glas.")
            st.write("Doch dieser Tisch, der hat vier Räder. Die Alkocops, sie geben Gas.")
            st.write("Das Dolce Vita soll es sein, man tritt in die Pedale,")
            st.write("Gen Italien lenkt man ein, es sprudelt aus der Zapfanlage.")
            st.write(" ")
            st.write("Mit dem Bierbike über die Alpen ")
            st.write("Rotzevoll nach Rimini")
            st.write("Mit dem Bierbike über die Alpen ")
            st.write("Rotzevoll nach Rimini")
            st.write("")
            st.write("Die Alkocops sind vollgetankt, und das auch ziemlich exzessiv.")
            st.write("Wie einst der große Hannibal bezwingen sie das Felsmassiv.")
            st.write("Seit dem ersten Kilometer träumen sie von Sangria,")
            st.write("Eimerweise einverleiben, ist doch sonnenklar.")
            st.write("")
            st.write("Mit dem Bierbike über die Alpen ")
            st.write("Rotzevoll nach Rimini")
            st.write("Mit dem Bierbike über die Alpen ")
            st.write("Rotzevoll nach Rimini")
            st.write("")
            st.write("Die Jungs sind motiviert und freuen sich auf das Meer,")
            st.write("Doch nach einem Kilometer ist ihr Tank schon wieder leer.")
            st.write("Die Waden schmerzen füchterlich, der Durst nicht aushaltbar.")
            st.write("Da erscheint ihnen Jesus und macht den Jungs was klar:")
            st.write("")
            st.write("Jesus: „Jungs, um euch zu besaufen müsst ihr nicht bis nach Rimini fahren.")
            st.write("Gutes Bier und Sangria gibt es an jeder Tankstelle.")
            st.write("Oder im Penny. Auf der Reeperbahn auch sonntags.“")
            st.write("")
            st.write("Mit dem Bierbike bis zur Tanke")
            st.write("Rotzevoll und Dosenbier")
            st.write("Mit dem Bierbike bis zur Tanke")
            st.write("Rotzevoll und Dosenbier")
            st.write("")
            st.write("")
            st.write("")