import requests
import streamlit as st
from streamlit_option_menu import option_menu
from streamlit_lottie import st_lottie
from streamlit_extras.let_it_rain import rain
from PIL import Image
from pyairtable import Api, Table
from streamlit import secrets
from datetime import datetime


# --- Konfiguration ---
st.set_page_config(page_title="Die Alkocops", page_icon="🍺", layout="wide")

def load_lottieurl(url):
    r = requests.get(url)
    if r.status_code != 200:
        return None
    return r.json()

# Use local CSS
def local_css(file_name):
    with open(file_name) as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

local_css("style/style.css")


# --- AIRTABLE ---

# Airtable Zugangsdaten (aus secrets.toml)
AIRTABLE_PAT = st.secrets["airtable"]["pat"]
AIRTABLE_BASE_ID = st.secrets["airtable"]["base_id"]

api = Api(AIRTABLE_PAT)
comments_table = api.base(AIRTABLE_BASE_ID).table("Comments")
counter_table = api.base(AIRTABLE_BASE_ID).table("Counter")

# === Counter-Funktion ===

def get_bier_count():
    record = counter_table.first(formula="{id} = '1'")
    if record:
        return record["fields"].get("count", 0), record["id"]
    else:
        return 0, None

def increment_bier_count(record_id, count):
    if record_id:
        new_count = count + 1
        counter_table.update(record_id, {"count": new_count})
        return new_count
    else:
        return count

# === Kommentar-Funktionen ===
def add_comment(text):
    comments_table.create({
        "text": text,
        "timestamp": datetime.now().isoformat(timespec="seconds")
    })

def get_comments():
    records = comments_table.all(sort=["-timestamp"])
    return [
        {
            "text": r["fields"].get("text", ""),
            "timestamp": r["fields"].get("timestamp", "")
        }
        for r in records
    ]

# ---- LOAD ASSETS ----
lottie_rock = load_lottieurl("https://lottie.host/c27869d1-603f-4f6e-9b91-fc2cf17c128d/xnNh83q1DP.json")
lottie_bier = load_lottieurl("https://lottie.host/95df498a-2d7a-4abb-8eb3-a8542f8759f7/Mbflv91AhA.json")

img_band1 = Image.open("images/foto1.jpg")
img_band2 = Image.open("images/foto2.jpg")

html_code_spotify_gold = '''
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7A8sWVqk8OE2HK3ucqyDt8?utm_source=generator&theme=0" width="100%" height="600" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
'''

html_code_spotify_stimmt = '''
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2vqyy6D0svzOw9JgJ8p0Eu?utm_source=generator&theme=0" width="100%" height="600" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
'''

html_code_live = '''
<iframe width="560" height="315" src="https://www.youtube.com/embed/pCQnWvyQ54Y?si=O-3ZX5K6sSvNA9wP&amp;controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
'''

st.title("Die Alkocops 🍻👮‍♂️")
tab_titles = [
    "Start",
    "Konzerte",
    "Texte",
    "Community"
]

tabs = st.tabs(tab_titles)

with tabs[0]:
    with st.container():
        text_column, image_column = st.columns(2)
        with text_column:
            st.subheader("¿Qué pasa cabrones?")
            st.title("Wir sind die Alkocops! 🍻")
            st.write("Ob Wohnungsmarkt, Clubsterben oder Craftbier: Die Alkocops haben etwas dagegen. Laut ChatGPT sind ihre Lieder wohl eine ''sozialkritische Faust ins Gesicht'', aber bescheiden wie sie sind, konzentrieren sie sich lieber auf das Wesentliche: Dosenbier verhaften!")
            st.write("")
            st.write("Die Alkocops sind Florian Silberblick, Huckleberry Gin, Marius Müller-Thurgau, Dr. Don Promillo und Toni Pilsetti.")
            st.write("")
            st.write("[ 📸 Instagram >](https://www.instagram.com/alkocops/?hl=de)")
            st.write("[ 🎵 Spotify >](https://open.spotify.com/intl-de/artist/6UolTF33q9gCE3kDK6tuTU?si=up3DRDMuQs6PF3vsJ1ZHhQ)")
            st.write("[ 🏕 Bandcamp >](https://diealkocops.bandcamp.com/)")
            st.write("[ 🎥 YouTube >](https://www.youtube.com/@diealkocops6613)")
            st.write("")
        with image_column:
            st.image(img_band2)

# ---- SPOTIFY - STIMMT SO ----
    with st.container():
        st.write("---")
        left_column, right_column = st.columns(2)
        with left_column:
            st.header("Stimmt So.")
            st.write("Die Punk-Manufaktur ''Die Alkocops'' liefert mit ihrem neuen Premium-Album wieder ab und überzeugt erneut mit einem feinperligen Geschmack und erstklassigen Zutaten. ''Stimmt So'' entführt euch auf eine musikalische Reise, die euch beim Saufduell in eurer Lieblingskneipe abholt, euch bis nach Pjöngjang führt und euch höchst euphorisiert wieder vor der Freiburger Haustür absetzt.")
            st.write("Neben zahlreichen Selbstreferenzen (Geile Band, Kieferchirurg, Verbotene Liebe, Marius ist jetzt tot) und Seitenhieben gegen den Franken-Machiavelli Markus Söder oder Radiogesicht Mark Forster beantworten die Alkocops auch die Frage ''Warum bin ich so ein Arschloch?''.")
            st.write("Am Ende bleibt nur zu sagen: ''Stimmt So.'' ist das Premium-Album für alle, die denken, Craft-Bier sei Bier, das mit Protein-Pulver gemischt wurde. Also ein Premium-Album für all die Leute, die feine Beobachtungen genauso sehr schätzen wie eine Faust in Mark Forsters Gesicht. Ein Album, das provoziert, amüsiert und euch garantiert in den Bann zieht - Alkocops eben.")
            st.write("")
        with right_column:
            st.write(html_code_spotify_stimmt, unsafe_allow_html=True)


    # ---- SPOTIFY - FLÜSSIGES GOLD----
    with st.container():
        st.write("---")
        right_column, left_column = st.columns(2)
        with left_column:
            st.header("Flüssiges Gold")
            st.write("Goldfarben, naturtrüb und mit einem vollen, intensiven Geschmack - das Album ''Flüssiges Gold'' von den Alkocops ist eine ehrliche Erfrischung, die keine Kompromisse eingeht. Der Klang dieses Albums ist ebenso charakterstark wie das Getränk, nach dem es benannt ist: vollmundig, kraftvoll und dabei stets authentisch. Flüssiges Gold entsteht nur, wenn man das Beste von allem vereint, ohne dabei Kompromisse zu machen.")
            st.write("Für all jene, die sich nur mit dem Besten zufriedengeben und deren Herz für fein abgestimmte Klangnuancen schlägt, ist dieses Album wie ein Fest für die Sinne. Wir legen großen Wert auf das Wohl anspruchsvoller Kenner, die wissen, dass es nicht einfach nur um Musik, sondern um ein Erlebnis geht, das in jeder Note spürbar wird. Flüssiges Gold soll immer das bleiben, was es bereits ist und als solches geschätzt wird: eines der süffigsten, genussvollsten Alben unserer Zeit.")
            st.write("")
        with right_column:
            st.write(html_code_spotify_gold, unsafe_allow_html=True)

with tabs[1]:
# ---- KONZERTE ---- 
    rain(
        emoji="🍻",
        font_size=54,
        falling_speed=5,
        animation_length="infinite",
    )
    with st.container():
        left_column, right_column = st.columns(2)
        with right_column:
            st.write(html_code_live, unsafe_allow_html=True) 
        with left_column:
            st.header("Konzerte")
            st.subheader("2025:")
            st.write("25.10. // Schlosskeller Emmendingen // tba")
            st.write("13.09. // Reihern im Roggen // Irgendwo im Saarland")
            st.write("11.07. // Binger Open Air")
            st.write("07.07. // Café Atlantik Freiburg // Maid Of Ace")
            st.subheader("2024:")
            st.write("02.11. // Jugendzentrum Denzlingen // Enraged Minority und Don Fritte")
            st.write("18.10. // YouRock Emmendingen // Rawside und Die Sprittler")
            st.write("21.09. // Hardcore Vol. 1 im Jugendhaus Heideplatz Frankfurt // The North End und Coppola")
            st.write("29.06. // Insterburg Karlsruhe // xxxxxxxxxxxxxxxx")
            st.write("18.05. // Punkrock Heimspiel Vol. 2 im Sonnenkeller Balingen // The Snouts und Der Ganze Rest")
            st.write("05.04. // Schlosskeller Emmendingen // Wagner Brutal")
            st.write("23.03. // Laut für Vielfalt! im SAK Lörrach // Skabooom")
            st.write("09.03. // Schlosskeller Emmendingen // Nevermind")
            st.write("")
            st.subheader("2023:")
            st.write("15.12. // Support your local subculture im Crash Freiburg // 80 Nails")
            st.write("09.08. // Café Atlantik Freiburg // Maid of Ace")
            st.write("22.04. // Battle to Exist in der Alten VHS Bonn // Die Manfreds")
            st.write("")
            st.subheader("2022:")
            st.write("19.11. // Schlosskeller Emmendingen // The Snouts & Skaboom")
            st.write("05.11. // DISTROY Festival in der KTS Freiburg // ")
            st.write("21.10. // Rockcafé Altdorf // KID-O")
            st.write("24.09. // Eimer Freiburg // Area South")
            st.write("08.07. // Reboot Festival im Eschholzpark Freiburg // ")
            st.write("26.06. // Freiburg stimmt ein im Artik Freiburg // ")
            st.write("18.06. // Cool Club Kinderweide in Königsfeld // Skabooom")
            st.write("14.05. // Album-Release-Party im JuZe Emmendingen // Skabooom")
            st.write("")
            st.subheader("2021:")
            st.write("16.10. // JuZe Denzlingen // Skabooom & Zirka")
            st.write("04.07. // Freiburg stimmt ein im Artik Freiburg // ")
            st.write("")
            st.subheader("2020:")
            st.write("09.05. // Corona-Livestream aus dem JuZe Emmendingen // ")
            st.write("")
            st.subheader("2019:")
            st.write("23.06. // KTS Freiburg // Heavy Kind & Vain")
            st.write("06.04. // Hinterhaus Emmendingen // ")        
            st.write("Irgendwann mal // White Rabbit Freiburg // ")
            st.write("")
            st.subheader("2018:")
            st.write("29.09. // Jugendzentrum Stühlinger // The Privateers")
            st.write("15.08. // White Rabbit Freiburg // ")
            st.write("")

with tabs[2]:
# --- LYRICS ---
    left_column, right_column = st.columns(2)
    with left_column:
            st.subheader("Saufduell (Triplebockfieber)")
            st.write("In der heimlichen Kneipe, so soll es sein.")
            st.write("Kein Störenfried redet auf mich ein.")
            st.write("Ich genieße die Kaltschale, so übertrieben.")
            st.write("Nichts kann diesen Moment der Freude trüben.")
            st.write("Doch plötzlich hat mich so ein Fremder erkannt.")
            st.write("Er hält meinem Blick eisern stand.")
            st.write("Was ist los mit dir? Bin ich ein Passbildautomat? ")
            st.write("Oder hab' ich noch Reste vom Frühstück in meinem Bart?")
            st.write("")
            st.write("Saufduell, Saufduell!")
            st.write("Siehst du, wie ich mir das Tripelbock bestell?")
            st.write("Tripelbock ist wie ein normaler Bock mal drei, ")
            st.write("Diese Kneipe ist nicht groß genug für uns zwei.")
            st.write("Ich hab das Tripelbockfieber, das Tripelbockfieber, ")
            st.write("Tripelbock ist ein sehr schmackhaftes Getränk.")
            st.write("Ich hab das Tripelbockfieber, das Tripelbockfieber, ")
            st.write("denn Triplebock ist ein sehr schmackhaftes Getränk")
            st.write("")
            st.write("Der Lümmel fordert mich raus zum Saufduell")
            st.write("Als ich es begriff, erfolgt die Reaktion schnell.")
            st.write("Ich hab mir ein Pils an den Tisch bestellt")
            st.write("Und hab es mir direkt in den Kopf gestellt.")
            st.write("Doch der Frechdachs gafft mich weiterhin an")
            st.write("Denkt er wirklich, dass er's mit mir aufnehmen kann?")
            st.write("Ich ruf: Garcon, schaff dein Tripelbock heran")
            st.write("Er kann doch nicht? Doch, er kann! ")
            st.write("")
            st.write("Das Sichtfeld verschwimmt, doch der Blickkontakt besteht? ")
            st.write("Hat meine Wahrnehmung die Realität verfehlt?")
            st.write("Der Wirt hat einen neuen Spiegel installiert. ")
            st.write("Im Tripelbockfieber hab ich das nicht kapiert.")
            st.write("")
            st.write("Der Lümmel fordert mich raus zum Saufduell")
            st.write("Als ich es begriff, erfolgt die Reaktion schnell.")
            st.write("Ich hab mir ein Pils an den Tisch bestellt")
            st.write("Und hab es mir direkt in den Kopf gestellt.")
            st.write("Doch der Frechdachs gafft mich weiterhin an")
            st.write("Denkt er wirklich, dass er's mit mir aufnehmen kann?")
            st.write("Ich ruf: Garcon, schaff dein Tripelbock heran")
            st.write("Er kann doch nicht? Doch, er kann! ")
            st.write("")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Geile Band")
            st.write("Du und deine Freunde, ihr habt eine Band,")
            st.write("Doch ihr seid hässlich, kein Wunder, dass euch keiner kennt.")
            st.write("Noten könnt ihr zwar lesen, Triolen kein Problem, ")
            st.write("Doch euren Pisspott-Schnitt will doch keiner sehen.")
            st.write("Du und deine Freunde gehen bald auf Tournee, ")
            st.write("Doch euch fehlt ein Sunnyboy, ein Typ aus St. Tropez.")
            st.write("Indie könnt ihr spielen, alles fresh und hip und new, ")
            st.write("So viel Geld und Schönheit, nur die Alkocrew.")
            st.write("")
            st.write("Alkocops sind ne geile Band, denn sie sehen gut aus. ")
            st.write("Sie spielen vor Millionen und lachen euch aus.")
            st.write("Andere Bands sehen scheiße aus, damit sind sie raus. ")
            st.write("Du kannst keine Musik machen, du bist ein Körperklaus.")
            st.write("")
            st.write("Wir und unsere Kumpels, so wie Gott uns schuf, ")
            st.write("zeigen euch wie's geht, amazing von Beruf.")
            st.write("Wir brauchen keinen Glamour, wir glitzern schon genug. ")
            st.write("Man hört die anderen schreien: Das ist doch Betrug.")
            st.write("Wir lassen euch natürlich hängen, schön und cool seid ihr nicht. ")
            st.write("Ihr nennt uns Poprock-Schmusestars, wir sehen uns vor Gericht.")
            st.write("Die Plattenfirma hinter uns, uns gibt es nicht für lau. ")
            st.write("Wer uns Punkverräter nennt, den machen wir zur Sau")
            st.write("Ich ruf: Garcon, schaff dein Tripelbock heran")
            st.write("Er kann doch nicht? Doch, er kann! ")            
            st.write("")
            st.write("Alkocops sind ne geile Band, denn sie sehen gut aus. ")
            st.write("Sie spielen vor Millionen und lachen euch aus.")
            st.write("Andere Bands sehen scheiße aus, damit sind sie raus. ")
            st.write("Du kannst keine Musik machen, du bist ein Körperklaus.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Hashtag Hurensohn")
            st.write("Ich lüg euch ins Gesicht, was lustig ist, denn ihr wisst es nicht.")
            st.write("Ich aber auch nicht, denn ich bin dumm, check nichts von dem um mich herum.")
            st.write("Instagram-Hurensohn, eure Freundschaft ist mein Lohn.")
            st.write("Joke, ist es nicht, sondern viel Geld. Wer hat versteckte Werbung bestellt?")
            st.write("")
            st.write("Ich werde niemals arbeiten gehen.")
            st.write("Ich werde niemals vor 10 Uhr aufstehen.")
            st.write("Nicht einen Finger werd' ich jemals krümmen, ")
            st.write("Das würde nur meine Laune verstimmen.")
            st.write("")
            st.write("(Mein ganzes) Geld brauch' ich für mich alleine, steuern Zahl ich sicher keine.")
            st.write("Wieso sollte ich, davon hab ich nichts, dieses Konzept versteh' ich nicht.")
            st.write("Fanpost tu ich auch nicht lesen, bei den Nazis wär ich dabei gewesen.")
            st.write("Doch bei Nazis (denen) ist Geld stets knapp, deshalb hänge ich lieber in Dubai ab.")
            st.write("")
            st.write("Ich werde niemals arbeiten gehen.")
            st.write("Ich werde niemals vor 10 Uhr aufstehen.")
            st.write("Nicht einen Finger werd' ich jemals krümmen, ")
            st.write("Das würde nur meine Laune verstimmen.")
            st.write("")
            st.write("Also Flotze123, wir geben dir zehn Dollar und dafür musst du in deinem nächsten Video nur kurz erwähnen, wie geil unsere Kinderkrippe aus Müllsäcken und Chemieabfällen ist und uns deine Seele geben. ")
            st.write("(Flotze123:) Jaja laber mich nicht voll, her mit der Kohle, ich liebe Kohle")
            st.write("")
            st.write("Ich werde niemals arbeiten gehen.")
            st.write("Ich werde niemals vor 10 Uhr aufstehen.")
            st.write("Nicht einen Finger werd' ich jemals krümmen, ")
            st.write("Das würde nur meine Laune verstimmen.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Have Fun In Pjöngjang")
            st.write("Nach 11, 12 oder 13 Jahren Ist es endlich mal soweit.")
            st.write("Papi spart für dich dein ganzes Leben, der Fjällraven Rucksack, er steht bereit.")
            st.write("Die Schulzeit war nur purer Stress, Ein Nebenjob raubt dir die Kraft.")
            st.write("Aber jetzt willst du die Welt erkunden, bei Onkel Kim in Untersuchungshaft.")
            st.write("")
            st.write("Only work, but no travel. Tony schickt dich ganz weit weg.")
            st.write("work work work, but no travel Have fun in Pjöngjang")
            st.write("")
            st.write("Lisa ist ein toughes Mädel, Australien und Thailand, da war sie schon.")
            st.write("Actionreisen sind jetzt voll im Trend, Experience nen geilen Hungerlohn.")
            st.write("Sie spricht jetzt fließend Koreanisch, 20 Stunden und kein Ende in Sicht.")
            st.write("So much individuality, auch Franzi und der Justus besuchen dich.")
            st.write("")
            st.write("Only work, but no travel. Tony schickt dich ganz weit weg.")
            st.write("work work work, but no travel Have fun in Pjöngjang")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Abrechnung zum Fest mit Mark Forster")
            st.write("Weihnachten, die Zeit des Gebens. Und dieses Jahr gibt's ein paar aufs Maul.")
            st.write("Alle spüren die Aggression am Tag der Geburt von Gottes Sohn.")
            st.write("Was nützt uns die Zeit der Liebe, wenn Mark Foster auch was davon hat?")
            st.write("Es erscheint nur völlig logisch: Wir hauen ihm seine Fresse (Brille) platt.")
            st.write("")
            st.write("Mark Foster wird das Fest verderben, darum muss er verdroschen werden.")
            st.write("Kein Glühwein mehr am Glühweinstand, dafür immer noch Dosenpfand.")
            st.write("Mark Foster will allen die Freude rauben, weil er keine Freunde hat.")
            st.write("Er hat so förmlich darum gebeten, ihn in sein Gesicht zu treten.")
            st.write("")
            st.write("Mark Foster ist ein Satanist. Ich sag's so, weil's die Wahrheit ist.")
            st.write("Er leitet einen Teufelskult, deswegen ist alles seine Schuld.")
            st.write("Mit der Macht des Lords im Herzen bereiten wir Mark Forster Schmerzen.")
            st.write("Keine Absolution am Tag der Geburt von Gottes Sohn")
            st.write("")
            st.write("Ja, Mark Foster ist eine richtig dumme Sau, weswegen ich ihm eins auf seine Fresse hau.")
            st.write("Morgen kann er zehn Minuten länger schlafen, denn er kann sich das Zähneputzen sparen. ")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Craftbeertrinker")
            st.write("Craft Bier Trinker haben keine Ehre")
            st.write("Sind schlimmer als jeder Weinexperte.")
            st.write("Sie tragen auf dem T-Shirt dumme Sprüche")
            st.write("Stehen am Grill, aber niemals in der Küche")
            st.write("Sie reden über diverse Wasserhärten")
            st.write("Und zupfen sich Pulled Pork aus ihren Ziegenbärten")
            st.write("In ihren Rachen schütten sie sich die Beize")
            st.write("Ich stelle mir die Frage, warum trinkst du diese Scheiße?")
            st.write("")
            st.write("Ich trinke Cratfbeer")
            st.write("Weil ich ein Arschloch bin.")
            st.write("")
            st.write("Nach sieben Craft Bier entgleitet ihr Gewissen")
            st.write("Und sie werden neben deine Schüssel pissen")
            st.write("Craft Bier Trinker lädt man nicht ein zum Feiern")
            st.write("Denn sie jubeln unironisch für den FC Bayern")
            st.write("Craft Bier Trinker loben sich gern' selbst ")
            st.write("Von Wohnungslosen fordern sie Wechselgeld")
            st.write("In ihren Rachen schütten sie sich die Beize")
            st.write("Ich stelle mir die Frage, warum trinkst du diese Scheiße?")
            st.write("Refrain")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Franken-Machiavelli")
            st.write("Er hatte es versprochen, nun ist es passiert.")
            st.write("Die Mietpreisbremse ist gefallen und Markus lässt die Korken knallen.")
            st.write("Die bayrische Landeswahl brachte ihm die Machtposition,")
            st.write("von da an intrigierte er gegen Klimaschutz und Mindestlohn.")
            st.write("")
            st.write("")
            st.write("Franken-Machiavelli - Einmarsch in dein Herz.")
            st.write("Er nimmt dir alles weg, doch du gibst es ihm gern.")
            st.write("Franken-Machiavelli - ist noch Mensch geblieben.")
            st.write("Mit seinem sexy Machtinstinkt, wie kann man ihn nicht lieben?")
            st.write("")
            st.write("Die unsichtbare Hand begrabscht dich wüst in deinem Schritt, ")
            st.write("während dir der Franken-Machiavelli von hinten in die Nüsse tritt.")
            st.write("Du liegst auf dem Boden, kommst aus der Freude nicht mehr raus: ")
            st.write("Der Sonnenkönig Bayerns zu Gast in deinem Haus.")
            st.write("")
            st.write("Völker, hört die Signale, auf zum letzten Gefecht. ")
            st.write("Die liberale Marktwirtschaft ist total gerecht.")
            st.write("Links-grün versiffte Stalinisten, das ist ja wohl ein Scherz. ")
            st.write("Zum Glück hat Markus einen Freund: Genosse Friedrich Merz.")
            st.write("(im Hintergrund: Marschierende Arbeiter)")
            st.write("")
            st.write("Franken-Machiavelli - schaut derweil in deim Herz vorbei")
            st.write("Er tritt dir in die Nüsse und ist dann mal so frei.")
            st.write("Franken-Machiavelli - auf zum letzten Gefecht.")
            st.write("Die liberale Marktwirtschaft: ich glaub, mir ist schlecht")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Kieferchirurg")
            st.write("Es ist wieder Wochenende, dumme Deutsche gehen auf Tour. ")
            st.write("Doch für eine kleine Gruppe ist es wieder Horror pur.")
            st.write("Mischgetränke, Mate-Tee. Kontrolle, die muss dann sein. ")
            st.write("Keine Biere, keine Chance, wer keins trinkt, der fährt gleich heim (ein)")
            st.write("Sieht der Doktor null Prozent, zieht er den Knüppel ziemlich schnell, ")
            st.write("Seine Wut schießt in die Höhe, Welcome to the Fist of Hell.")
            st.write("Flocke muss ihn dann beruhigen, bietet ihm ein Pilschen an, ")
            st.write("Dann glätten sich die Wogen, doch der nächste ist gleich dran.")
            st.write("")
            st.write("Alkocops, sie bleiben sich treu, trinken stets das Hefebräu.")
            st.write("Don Promillo ist ein Kieferchirurg, der sich selbst mit Kundschaft versorgt.")
            st.write("")
            st.write("Don Promillo kanns nicht fassen, früher gabs mehr Keilerei. ")
            st.write("Dafür müssen sie nun sorgen, Hallo Alkopolizei.")
            st.write("Was denkt sich denn diese Jugend, wenn sie ein Pils verschmäht? ")
            st.write("Toni schüttelt nur den Kopf, ach verfickt und zugenäht.")
            st.write("Ist es schon 20:30, trotzdem noch keiner dicht? ")
            st.write("Das schreit nach OP-Aktion mit seiner Faust in deinem Gesicht.")
            st.write("Sie machen deutlich Überstunden, Burnout ist vorprogrammiert. ")
            st.write("Feierabend kommt schon bald (wie das duftet), wenn der Don dann notoperiert")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Erzähl' mir Nichts!")
            st.write("Der größte Punk aus Wattenscheid")
            st.write("Den Iro trägt er schon lang nicht mehr")
            st.write("Als Kanzler war er mal bereit")
            st.write("Atomkraft liebt er doch so sehr")
            st.write("Das schlimmste ist nicht eingetreten")
            st.write("Bier gibt es noch weit und breit")
            st.write("Parteibuch rot, Gendern nervt")
            st.write("Der Karies am Zahn der Zeit")
            st.write("")
            st.write("Erzähl mir doch was neues, alter, weißer Mann")
            st.write("No future war gestern, Boomer Number 1")
            st.write("Erzähl mir nichts vom Leben, alter, weißer Mann")
            st.write("Anarchie und Alkohol, die Rente fängt (doch) bestimmt bald an")
            st.write("")
            st.write("Der andere Typ schoss mit Pistolen")
            st.write("Damals war er bunt und schrill")
            st.write("Trump würde er gern wieder holen")
            st.write("Er mag wohl den alten Drill")
            st.write("Konservativ und rassistisch")
            st.write("Der Brexit ist wohl nicht so schlimm")
            st.write("Er lies sich gehen, auch innerlich")
            st.write("Did God really save the queen")
            st.write("")
            st.write("Erzähl mir doch was neues, alter, weißer Mann")
            st.write("No future war gestern, Boomer Number 1")
            st.write("Erzähl mir nichts vom Leben, alter, weißer Mann")
            st.write("Anarchie und Alkohol, die Rente fängt (doch) bestimmt bald an")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Verbotene Liebe")
            st.write("Es ist die Sehnsucht, die in Don Promillo brennt, ")
            st.write("Denn er liebt jemand aus einer anderen Band.")
            st.write("Donny denkt, das macht nix, das ist doch normal, ")
            st.write("Doch er liegt falsch, denn das ist illegal.")
            st.write("")
            st.write("Nicht legal! Juristen sagen so, ")
            st.write("ist nunmal verboten, es ist halt so.")
            st.write("Als Verteidiger sind dir da die Hände gebunden, ")
            st.write("trotzdem tut der Don die Liebe erkunden.")
            st.write("")
            st.write("")
            st.write("Verbotene Liebe, es soll nicht sein, die Alkocops halten es daher streng geheim.")
            st.write("Verbotene Liebe, wider die Natur, Dr. Don Promillo, wie kannst du nur?")
            st.write("Verbotene Liebe, gemeißelt in Stein, eine solche Perversion wird für immer verboten sein. Verbotene Liebe, sagen alle so: ist nunmal verboten, du elendig dummer Wichser!")
            st.write("")
            st.write("Im Garten Eden der Baum der Leidenschaft, ")
            st.write("An ihm wird schamlos von Don Promillo (ihm) genascht.")
            st.write("Es ist ein Eklat, ein Sakrileg, ")
            st.write("Eine Sünde wie sie im Buche steht.")
            st.write("So falsch! könnte es der Herrgott sehn, ")
            st.write("Er würde auf drakonische Bestrafung bestehen. ")
            st.write("Doch Donny ist kein religiöser Mann, ")
            st.write("Weshalb er sich verbotene Liebe gönnen kann.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Marius Ist Jetzt Tot")
            st.write("Tränen fließen langsam über die frisch gestraffte Haut, ")
            st.write("Mit jedem Tropfen der Gedanke, man hat ihn uns geraubt.")
            st.write("Es ist ein Tag der Trauer, denn Marius ist tot. ")
            st.write("Gestorben, wie er lebte: auf einem langen Boot.")
            st.write("")
            st.write("Ein Miethai, der nicht schwimmen kann, versinkt wie ein Stein im Ozean. ")
            st.write("Die Last, sie wiegt zu schwer, doch das ist jetzt kein Problem mehr. ")
            st.write("Das Koka in den Kopf geschossen, verspeist von seinen Artgenossen, ")
            st.write("die See verfärbt sich rot, und Marius ist jetzt tot.")
            st.write("")
            st.write("")
            st.write("Seine letzte Nacht (unter uns) verbrachte er auf seiner Yacht. ")
            st.write("Alle waren eingeladen, hatten gute Laune mitgebracht.")
            st.write("Seinen Verstand verlor Marius (er) im Disco-Schnee-Gestöber, ")
            st.write("Bis zum Haarschopf zugedröhnt, unternahm er ein tödliches Manöver.")
            st.write("")
            st.write("Ein Miethai, der nicht schwimmen kann, versinkt wie ein Stein im Ozean. ")
            st.write("Die Last, sie wiegt zu schwer, doch das ist jetzt kein Problem mehr. ")
            st.write("Das Koka in den Kopf geschossen, verspeist von seinen Artgenossen, ")
            st.write("die See verfärbt sich rot, und Marius ist jetzt tot.")
            st.write("")
            st.write("Wie im Film Titanic stand Marius am Bug.")
            st.write("Breitete die Arme aus und rief den Wellen zu: ")
            st.write("''Ich bin der König dieser Welt! Das Meer, es kann mir nichts!''")
            st.write("Doch plötzlich traf ihn eine Welle im sympathischen Gesicht. ")
            st.write("Die Welle packte ihn und riss ihn mit, man hörte nur einen Schrei.")
            st.write("Sein Leben frisch begonnen - und nun ist es vorbei. ")
            st.write("")
            st.write("Ein Miethai, der nicht schwimmen kann, versinkt wie ein Stein im Ozean. ")
            st.write("Die Last, sie wiegt zu schwer, doch das ist jetzt kein Problem mehr. ")
            st.write("Das Koka in den Kopf geschossen, verspeist von seinen Artgenossen. ")
            st.write("Er lebt auf Ewig kostenlos, tief drin in Poseidons Schoß.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Freiburger Nächte")
            st.write("Ich sitz' schon seit 'ner Stunde ziemlich dumm")
            st.write("Allein in einer Kneipe Freiburgs rum.")
            st.write("Hab' Lust zum Feiern, aber weiß nicht wo,")
            st.write("Denn Freiburgs Nachtleben ist ein Griff ins Klo.")
            st.write("Ein Thekenbruder meint, er wisse, wo was geht.")
            st.write("Soll mich beeilen, sonst sei es zu spät.")
            st.write("Doch ein Anwohner ist schneller, meint, er bräuchte seine Ruh'")
            st.write("Und wieder macht ein Freiburger Club zu.")
            st.write("")
            st.write("Freiburger Nächte sind kurz.")
            st.write("Freiburger Nächte sind kurz.")
            st.write("In Freiburg wird es nachts einfach still,")
            st.write("Weil der Anwohner es eben so will.")
            st.write("")
            st.write("Früh morgens wach ich auf, 16 Uhr 10.")
            st.write("Kippen alle, Flasche leer, kein Problem.")
            st.write("Seit gestern haben wir 'nen Späti hier.")
            st.write("Versorgt das Viertel mit echtem Premiumbier.")
            st.write("Mit Kater bezwing' ich den Schlossberg jetzt")
            st.write("Doch an der Ecke stelle ich leider fest:")
            st.write("Gestern macht hier erst ein Späti auf")
            st.write("Und heute ist die Anzeige schon raus.")
            st.write("")
            st.write("Freiburger Nächte sind kurz.")
            st.write("Freiburger Nächte sind kurz.")
            st.write("In Freiburg wird es nachts einfach still,")
            st.write("Weil der Anwohner es eben so will.")            
            st.write("")
            st.write("")
            st.write("")
    with right_column:
            st.subheader("Viva Alkocops")
            st.write("Wer hat ein Mittel gegen Krebs entdeckt? ")
            st.write("Vor wem hat selbst Bushido Respekt?")
            st.write("Und ihr Bankkonto ist immer im grünen Bereich, ")
            st.write("Manche werden schon bei der Erwähnung feucht!")
            st.write("Wenn irgendein blinder Bayer in der Bundesliga trifft,")
            st.write("Widmet er Ihnen stets das räudige Goal!")
            st.write("Und in Mathe hatten sie immer eine Eins, ")
            st.write("Nein, ein Autogramm geben sie dir keins.")
            st.write("")
            st.write("Es sind die Alkocops die duften Typen, ")
            st.write("Es sind die Alkocops, die Motherfucker des Undergrounds.")
            st.write("Viva Alkocops, Viva Alkocops, ")
            st.write("das Volk jubelt ihnen zu wie einem Diktator von 'nem Inselstaat.")
            st.write("")
            st.write("Sie sind die coolste Band hier in der Stadt, ")
            st.write("Sie machen in 'ner Keilerei an die hundert Studenten platt!")
            st.write("Wenn Merkel auf der Straße demonstriert, ")
            st.write("Kanalisiert sich ihre Wut: ''Danke Alkocops!''")
            st.write("Wer inspirierte sämtlichen sehr guten Songs? ")
            st.write("Wer verzichtet auf tribal shit und Bongo Drums?")
            st.write("Und ihr soziales Engagement verschämt selbst Bono von U2, ")
            st.write("Denn er ist ein Loser - genau wie du!")
            st.write("")
            st.write("Es sind die Alkocops die duften Typen, ")
            st.write("Es sind die Alkocops, die Motherfucker des Undergrounds.")
            st.write("Viva Alkocops, Viva Alkocops, das Volk jubelt ihnen zu wie dem Diktator von 'nem Inselstaat.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("FIFA")
            st.write("Zusammen chillt ihr in der Villa von eurem Oberlauch, ")
            st.write("Pinselt euch dabei gegenseitig den Bauch.")
            st.write("Durch die toten Hallen dringt ein fieses Lachen,")
            st.write("Thema der Sitzung heute: Wie kann man Fussball beschissen machen?")
            st.write("")
            st.write("UEFA, FIFA, was habt ihr geraucht?")
            st.write("Eure Symphatiepunkte habt ihr damit aufgebraucht!")
            st.write("Schiebung bei WM-Vergabe ist mir scheißegal,")
            st.write("Doch kein Bier im Stadion, das ist ein Skandal!")
            st.write("")
            st.write("Früher Profifussballspieler, jetzt ein Profihurensohn,")
            st.write("Ohne Fans kein Fussball. Undank ist der Weltenlohn")
            st.write("Auf der VIP-Tribüne zieht Waldi sich drei Weizen rein,")
            st.write("Wahre Fans verdursten, doch das interessiert keinen!")
            st.write("")
            st.write("UEFA, FIFA, was habt ihr geraucht?")
            st.write("Eure Symphatiepunkte habt ihr damit aufgebraucht!")
            st.write("Schiebung bei WM-Vergabe ist mir scheißegal,")
            st.write("Doch kein Bier im Stadion, das ist ein Skandal!")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Marius Müller Miethai")
            st.write("Es klopft an der Tür, jemand will hinein,")
            st.write("Das kann nur Marius Müller-Thurgau sein.")
            st.write("Er will seine Miete jetzt bar Kralle,")
            st.write("Du bist getappt in seine Mietpreisfalle.")
            st.write("Wie du kannst nicht zahlen? Mir kommen die Tränen,")
            st.write("Das entlockt dem Miethai nur ein müdes Gähnen.")
            st.write("In 24 Stunden tauchen die Gorillas auf")
            st.write("Und hauen auf deinen Schädel mit einem Basey drauf")
            st.write("")
            st.write("Der Wohnungsmarkt — ein Haifischbecken,")
            st.write("Du kannst dich nicht vor dem dicksten Hai verstecken.")
            st.write("Marius Müller-Thurgau hat dein Blut geleckt,")
            st.write("Er nährt sich an deinem Cash, es hat ihm gut geschmeckt.")
            st.write("")
            st.write("Die abgesiffte Winzwohnung im Monat tausend Steine,")
            st.write("Wie du kannst die nicht zahlen, dann bricht er dir die Beine.")
            st.write("Du hast nicht genug Kohle, doch du mühst dich sehr,")
            st.write("Marius scheißegal, dann arbeite halt mehr.")
            st.write("Er kommt in deine Wohnung, streicht dir einmal über die Wand,")
            st.write("Diese Renovierung war wichtig — Mietpreiserhöhung!")
            st.write("Du schuftest jeden Tag und deine Kinder Pfandpiraten.")
            st.write("Marius kauft ein paar Häuser, er kriegt einen Harten.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Die Bierhand Gottes")
            st.write("Samstagabend, endlich ist es soweit.")
            st.write("Die Woche ist beendet, zum Feiern bereit.")
            st.write("Seit Tagen freust du dich auf diesen Moment.")
            st.write("Mit deinen Freunden feiern, ganz in deinem Element.")
            st.write("Doch auf der Tanzfläche rückt dir jemand auf die Pelle.")
            st.write("Schlagartig bekommst du von hinten eine Schelle.")
            st.write("Mit Maxi solltest du dir es lieber nicht verkacken.")
            st.write("Die Bierhand Gottes landet in deinem Nacken!")
            st.write("")
            st.write("Die Bierhand Gottes sorgt für Gerechtigkeit,")
            st.write("Eine Schelle in den Nacken ist liebevoll gemeint!")
            st.write("Wer eine Bierhand abbekommt, hat sie auch verdient.")
            st.write("Also halt deine Klappe, für heute bist du bedient.")
            st.write("")
            st.write("Die Bierhand Gottes wacht nachts über der Stadt.")
            st.write("Wo immer Ungerechtigkeit passiert, macht sie die Ungerechten platt.")
            st.write("Vor der Bierhand Gottes werden große Menschen klein.")
            st.write("Was tanzt du auf meiner Tanzfläche - eine gerechte Strafe muss sein!")
            st.write("In die Handfläche wird ein Bier geschenkt und die Bierhand ist geladen,")
            st.write("Einmal richtig zugehauen und schon geht dein Nacken baden.")
            st.write("Man sieht sie nicht kommen. Plötzlich wird es feucht am Kragen.")
            st.write("Die Bierhand Gottes hat wieder einmal zugeschlagen. ")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Mit der Fußmaschine zur Tanke")
            st.write("Diesen Sommer gibt es die Empfehlung")
            st.write("Zu Urlaub in der heimischen Region,")
            st.write("Das ist für mich von Vorteil,")
            st.write("Denn die wichtigsten Urlaubsziele kenne ich schon:")
            st.write("Shell natürlich und Tankhof Grün")
            st.write("Und auf jeden Fall insbesondere Aral.")
            st.write("Sie verkaufen das Wasser des Urlaubs")
            st.write("Zur Befüllung vom knochentrockenen Kanal")
            st.write("")
            st.write("Mit der Fußmaschine zur Tanke, ")
            st.write("Dosenbier kaufen der Gedanke.")
            st.write("Gib' die Kaltschale jetzt endlich her,")
            st.write("Es dürstet mich - sehr!")
            st.write("Mit der Fußmaschine zur Tanke,")
            st.write("Billiges Dosenbier. Bitteschön, Danke. ")
            st.write("Komm mal her jetzt, ich hab' Kaltschalen bestellt,")
            st.write("Und nimm dafür mein rotes Kleingeld.")
            st.write("")
            st.write("An der Tanke kauf' ich sicher kein Craftbier")
            st.write("Und auch keinen Fall Club Mate,")
            st.write("Wenn der Tankwart mir das anbietet,")
            st.write("Würde ich ihn verprügeln!")
            st.write("Das ist a) nämlich viel zu teuer ")
            st.write("Und b) schmeckt's nach grindigem Kanal,")
            st.write("Im Gegensatz dazu überzeugt")
            st.write("Dosenbier im Geschmack total.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Jürgen Klinsmann")
            st.write("Neulich stand ich wie immer am Imbiss und aß eine 1-Meter-Bratwurst. ")
            st.write("Früher war ich hier immer zusammen, zusammen mit Jürgen Klinsmann. ")
            st.write("Wir teilten so ziemlich alles, tranken so manchen über den Durst. ")
            st.write("Doch heute bin ich alleine. Jürgen, was ist los mit dir?")
            st.write("")
            st.write("Ooooh - Jürgen Klinsmann, du hast dich sehr verändert.")
            st.write("Früher warst du ein gern gesehener Partygast, ")
            st.write("Doch heute bist du nicht mehr so cool! Ooooh - Jürgen Klinsmann, du hast dich sehr verändert: ")
            st.write("Früher warst du ein gern gesehener Partygast, ")
            st.write("doch heute spielst du DOTA 2. ")
            st.write("")
            st.write("Immer wenn man dich mal zufällig trifft, bist du voll auf Speed. ")
            st.write("Neulich hast du vergessen, mir zum Geburtstag zu gratulieren. ")
            st.write("Du versucht es, doch du entkommst der Realität nicht. ")
            st.write("Jürgen Klinsmann, bitte , komm zurück ans Licht!")
            st.write("")
            st.write("Ooooh - Jürgen Klinsmann, du hast dich sehr verändert: ")
            st.write("Früher spielten wir Federball, doch jetzt spielst du DOTA am PC. Ooooh - Jürgen Klinsmann, du hast dich sehr verändert: ")
            st.write("Früher spielten wir Laufen-Saufen, doch jetzt spielst High Card Low Card mit dir selbst!")
            st.write("")
            st.write("Ooooh - Jürgen Klinsmann, du hast dich sehr verändert: ")
            st.write("Doch ich gebe nicht auf. Ich kämpfe für dich. Ooooh - Jürgen Klinsmann, du hast dich sehr verändert: ")
            st.write("Gemeinsam schaffen wir es aus deiner Krise, alle zusammen Hand in Hand.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Reise nach Moncao")
            st.write("Fürst Big A und Marius gönnen sich in Monaco lecker Wein")
            st.write("Der nächste Impuls treibt sie in einen Saunaclub hinein. ")
            st.write("Sie verlassen den Club, die Schlampen werden geprellt")
            st.write("Wer hat drei Flaschen Möet auf meine Rechnung bestellt?")
            st.write(" Es ist Marius von den Alkocops, ")
            st.write("Er ist mit der High Society per du.")
            st.write("Er feiert in Monaco mit dem Fürsten und der Crew.")
            st.write("")
            st.write("Ein Champus-Wettsaufen wird von Marius losgetreten, ")
            st.write("Alles mit einem Adelstitel wird zur Teilnahme gebeten.  Marius gewinnt natürlich, wie könnte es anders sein? ")
            st.write("Trotzdem passt noch einiges an Drogen in ihn rein!")
            st.write(" Du bist doch mein bester Freund, lallt der Fürst im Suff.")
            st.write("Er kriegt ’nen fetten Schulterklapps. Junge, ist der Druff! ")
            st.write("Ich mag dich doch auch, du weißt, du bist mein Lieblingsfürst. ")
            st.write("Ich geh’ nochmal kurz an die Bar, ich habe noch etwas Durst. ")
            st.write("Der Fürst kriecht unter dem Tisch herum, denn er kann nicht mehr")
            st.write("Doch Marius lässt ihn nicht und holt noch zwei Bier her. ")
            st.write("Ob Monaco oder Mallotze, wo man sich bepichelt ist egal")
            st.write("Ob Designeranzug oder Badehose, alle asozial!")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Schönster Koch")
            st.write("Ich stehe vor dem Herd mit meiner Kochschürze an,")
            st.write("Vor mir hängt ein Spiegel, damit ich mich sehen kann.")
            st.write("Hinter mir ist eine Videokamera installiert,")
            st.write("Nach dem Kochen wird die Zeitlupe analysiert.")
            st.write("")
            st.write("Man nennt mich nicht umsonst den schönsten Koch,")
            st.write("Was ich koche schmeckt immer sehr gut,")
            st.write("Man nennt mich nicht umsonst den schönsten Koch,")
            st.write("Gesundes Essen ist meine Passion!")
            st.write("")
            st.write("Heute koche ich ein schmackhaftes Faust-Sandwich,")
            st.write("Dazu nutze ich natürlich den Sandwichmaker.")
            st.write("Jemand der behauptet ich sei nicht der schönste Koch,")
            st.write("Schönster-Koch-Fäuste-Vendetta")
            st.write("")
            st.write("Ein Proteingetränk und Wurst mit Ei,")
            st.write("Sind bei einer gesunden Ernährung dabei.")
            st.write("Kaffee und Spaghetti mit Tomatensoße,")
            st.write("Dazu ein bisschen Thunfisch aus der Dose.")
            st.write("Literweise Red Bull und ein Beutel Tabak")
            st.write("Runden dann eigentlich die Ernährung ab.")
            st.write("Wenn du davon dann Durchfall beziehst,")
            st.write("Dann ist das immer ein gutes Zeichen.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Wurstheimat")
            st.write("Machen sie die Schnauze auf platzen mir meine Ohren")
            st.write("Ehre, Stolz, Wurst und Heimat, welche Wurzeln gehen verloren?")
            st.write("Schreiben sie Kommentare geht main Puls auf 210")
            st.write("Sie filmen mich, das dürfen sie nicht. Ich will keine Blaubraunen sehen.")
            st.write("")
            st.write("Fick dich")
            st.write("Hässlich wie die Nacht")
            st.write("Grässlich, Glatze")
            st.write("Hab' dich ausgelacht")
            st.write("")
            st.write("Sie glauben an deutsche Tugend, trinken dennoch viel zu viel")
            st.write("Sind nur dicht und keine Denker. Uniformen ohne Stil. ")
            st.write("12 Jahre Fliegenschiss. Opa Gauland hat gepennt.")
            st.write("Stolz sein auf das Vaterland, weil man sonst nichts anderes kennt")
            st.write("")
            st.write("Ja ich weiß, man soll niemals Andere beleidigen")
            st.write("Doch bei so viel ekelhaften Rassismus und patriotischen Rumgewichse")
            st.write("Muss man auch mal die verbale Dummkeule schwingen")
            st.write("Was anderes verstehen die doch in ihren Sumpf eh nicht mehr")
            st.write("Die strunzdummen Amöben mit ihren Adolf-Tattoos und Bernd-Höcke-Actionfiguren.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Toni Motherfucker")
            st.write("Nachts auf der Straße, die Beleuchtung fällt aus.")
            st.write("Toni tritt aus dem Schatten heraus.")
            st.write("Meine Freunde nicht mehr da, wie kann das sein? ")
            st.write("Mein Hoden schrumpft in den Körper hinein!")
            st.write("Toni ist mächtig, das wird ihm bescheinigt.")
            st.write("Hätt' ich ihn doch nicht auf Facebook entliked.")
            st.write("Auf einmal wird mir klar, gleich beiß' ich ins Gras, ")
            st.write("Ein letzter Versuch: Toni war doch nur Spaß!")
            st.write("")
            st.write("Das verzweifelte Flehen funktioniert natürlich nicht, ")
            st.write("Die schaufelgroße Hand klatscht mir ins Gesicht.")
            st.write("Mein lauchiger Körper, er küsst den Asphalt, ")
            st.write("Ich merke, meine Hose wird nasskalt.")
            st.write("Wie dumm von mir, diese Respektlosigkeit, ")
            st.write("Wird seid jeher mit dem Tode verurteilt.")
            st.write("Das letzte was ich tu, ich bete zu Gott, ")
            st.write("Dann schlägt Toni mir ein Loch in meinen Kopf.")
            st.write("")
            st.write("1,2,3 Toni kommt vorbei ")
            st.write("Und schlägt dir dann dein Face zu Brei")
            st.write("Wenn du dreimal in den Spiegel Toni sprichst, ")
            st.write("Dann kommt er zu dir und tritt dir ins Gesicht.")
            st.write("")
            st.write("Toni Motherfucker.")
            st.write("Toni Motherfucker.")
            st.write("Toni Motherfucker.")
            st.write("Toni Crazy Motherfucker.")
            st.write("")
            st.write("")
            st.write("")
            st.subheader("Bierbike über die Alpen")
            st.write("Die Ellenbogen auf dem Tisch, die Hände fest am Glas.")
            st.write("Doch dieser Tisch, der hat vier Räder. Die Alkocops, sie geben Gas.")
            st.write("Das Dolce Vita soll es sein, man tritt in die Pedale,")
            st.write("Gen Italien lenkt man ein, es sprudelt aus der Zapfanlage.")
            st.write("")
            st.write("Mit dem Bierbike über die Alpen ")
            st.write("Rotzevoll nach Rimini")
            st.write("Mit dem Bierbike über die Alpen ")
            st.write("Rotzevoll nach Rimini")
            st.write("")
            st.write("Die Alkocops sind vollgetankt, und das auch ziemlich exzessiv.")
            st.write("Wie einst der große Hannibal bezwingen sie das Felsmassiv.")
            st.write("Seit dem ersten Kilometer träumen sie von Sangria,")
            st.write("Eimerweise einverleiben, ist doch sonnenklar.")
            st.write("")
            st.write("Mit dem Bierbike über die Alpen ")
            st.write("Rotzevoll nach Rimini")
            st.write("Mit dem Bierbike über die Alpen ")
            st.write("Rotzevoll nach Rimini")
            st.write("")
            st.write("Die Jungs sind motiviert und freuen sich auf das Meer,")
            st.write("Doch nach einem Kilometer ist ihr Tank schon wieder leer.")
            st.write("Die Waden schmerzen füchterlich, der Durst nicht aushaltbar.")
            st.write("Da erscheint ihnen Jesus und macht den Jungs was klar:")
            st.write("")
            st.write("Jesus: ''Jungs, um euch zu besaufen müsst ihr nicht bis nach Rimini fahren.")
            st.write("Gutes Bier und Sangria gibt es an jeder Tankstelle.")
            st.write("Oder im Penny. Auf der Reeperbahn auch sonntags.''")
            st.write("")
            st.write("Mit dem Bierbike bis zur Tanke")
            st.write("Rotzevoll und Dosenbier")
            st.write("Mit dem Bierbike bis zur Tanke")
            st.write("Rotzevoll und Dosenbier")
            st.write("")
            st.write("")
            st.write("")

with tabs[3]:
# Community
    count, record_id = get_bier_count()

    st.header("Community-Count: Hast du heute schon ein leckeres Bier getrunken?")

    if st.button("Ja, ich habe ein Bier getrunken! 🍻"):
        count = increment_bier_count(record_id, count)
        st.success(f"Vielen Dank, dass du uns mit deinem Bier unterstützt! 💕")

    st.subheader(f"Dank der zauberhaften Alkocops-Community wurden schon ***{count} Biere*** verhaftet! 🚓🚨")

    st.markdown("---")
    st.header("Kommentare 🫠")
    comment = st.text_area("Wie schmeckt dir Bier? Wann und wo hast du uns gesehen? Wie fandest du unseren Auftritt?")

    if st.button("Kommentar abschicken"):
        if comment.strip():
            add_comment(comment.strip())
            st.success("Danke für deinen Beitrag!Jetzt hol' dir ein Bier und erzähle deinen Freunden von den Alkocops!")
        else:
            st.warning("Boah, ey, du musst erstmal etwas schreiben, du Eumel!")

    st.markdown("### Kommentare")
    for c in get_comments():
        st.write(f"🕒 {c['timestamp']}  \n> {c['text']}")