name: Restart Streamlit App Daily

on:
  schedule:
    - cron: '0 6 * * *'  # Jeden Tag um 6 Uhr UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Git Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "chore: keepalive trigger"
          git push
